### ISSUE TITLE
How to use with Nuxt?

### ISSUE THREAD

**Issue by InstantlyMoist** [so1ve/vue-skinview3d#53]
Hi there,

I was wondering if this is usable with Nuxt?

Kind regards

**Comment by so1ve** [comment]
It should! If not, please provide a reproduction repo to help me debug. Thanks!

**Comment by InstantlyMoist** [comment]
Could you hook me up with an example? Im very new to Nuxt so I'm having a hard time figuring out how I should add it.

I attempted creating a Nuxt plugin and using doing Vue.useComponent(SkinRender3d) but it didn't seem like a working or the right solution.

**Comment by InstantlyMoist** [comment]
I created a plugin like this:
`import Vue from 'vue';
import { SkinView3d } from 'vue-skinview3d/index';

Vue.component('SkinView3d', SkinView3d);`

then imported it like this:
`  plugins: [
    "~/plugins/skinrender3d.ts",
  ],`
  
and attempted to use it like this
`<template>
  <div class="skin-tile">
    <canvas id="skin_container"></canvas>
    <img src="/skins/skin.png?url">
    <SkinView3d skin-url="/skins/skin.png?url" height="100" width="100"></SkinView3d>
  </div>
</template>

<script lang="ts">
export default {
  props: {
    skin_url: {
      type: Object,
      default: null
    },
    name: {
      type: String,
      default: null
    },
    description: {
      type: String,
      default: null
    },
  }
};

</script> 

<style lang="sass">
.skin-tile
  background-color: $primary
</style>`

**Comment by InstantlyMoist** [comment]
Managed to find the issue, seems to be working great. Thanks

**Comment by so1ve** [comment]
You don't have to register a global component, just import it and use in the template:

```vue
<script setup lang="ts">
import { SkinView3d } from "vue-skinview3d";
</script>

<template>
  <SkinView3d />
</template>
```
