### ISSUE TITLE
Abillity to hard-reset rotation

### ISSUE THREAD

**Issue by InstantlyMoist** [so1ve/vue-skinview3d#54]
Hi,

Is there a way to hard-reset the rotation on the skin. So if it stops auto-rotating I can snap it back into it's 'default' spot

**Comment by so1ve** [comment]
I'll look into this

**Comment by so1ve** [comment]
Hi @InstantlyMoist, I've looked into this feature request and I found I can do nothing in this project. You'd better file this issue in https://github.com/bs-community/skinview3d

**Comment by InstantlyMoist** [comment]
Would there be a way to call the 'resetCameraPos' method? Either way I'll make an issue for them. Thanks

**Comment by InstantlyMoist** [comment]
Thanks for your work so far, i've been trying to get it working within a component. But I'm failing miserably. I created a test.vue page and pasted the playground in there and it appears to work fine.

I call the component like this:
`<TilesSkinTile skinUrl="/skins/skin2.png?url" skinName="Test skin 2!" description="This is a test skin!"></TilesSkinTile>`

And I created a SkinTile.vue like this: https://pastebin.com/VAh1K2wk

It renders fine, the reset method just doesn't work. Debugging shows that the 'viewerRef' is null. This also happens when only adding the 'TilesSkinTile' once. Could this be an issue on my side?

**Comment by InstantlyMoist** [comment]
Stupid oversight from me, my bad; I missed the 'ref=viewerRef' part.

**Comment by so1ve** [comment]
Does it work now? 👀

**Comment by InstantlyMoist** [comment]
![image](https://github.com/so1ve/vue-skinview3d/assets/32609460/48f4d54c-f6e7-4ba4-b806-e5b3a68cda7b)

Hell yeah! Appreciate the help!
